version: '3.9'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      retries: 3
      timeout: 5s

  wordpress:
    depends_on:
      db:
        condition: service_healthy
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins

  wpcli:
    image: wordpress:cli
    depends_on:
      - wordpress
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
    entrypoint: ["wp"]
    command: ["--path=/var/www/html"]
    tty: true

volumes:
  db_data:
